In [1]:
import numpy as np
np.array([1,2,3,4,4])

array([1, 2, 3, 4, 4])

In [2]:
np.zeros

<function numpy.zeros>

In [10]:
np.random.random(30)

array([0.41683577, 0.29608854, 0.92736045, 0.44906435, 0.70285946,
       0.85974235, 0.11483865, 0.58502103, 0.67705502, 0.11933604,
       0.56524179, 0.83818955, 0.06018981, 0.69462351, 0.53925762,
       0.08012108, 0.58488128, 0.30707104, 0.85525262, 0.9160314 ,
       0.72578792, 0.38583997, 0.77217074, 0.30925481, 0.51379749,
       0.03223869, 0.04802132, 0.07226516, 0.31826554, 0.17422622])

In [11]:
# creat two arries : diatsance :100,20,300,400
# and speed 15,25,30,40
# and tell me the maximum time taken
# using array only

In [20]:
d=np.array([100,20,300,400])
s= np.array([15,25,30,40])
a= d/s
print(a)
max=np.max(a)
print(max)
# max= np.maximum(s)

[ 6.66666667  0.8        10.         10.        ]
10.0


In [29]:
dis=np.array([
            [100,20,300],
             [10,20,300],
             
             ])
print(dis)
speed =np.array([[1,3,4,],
                [2,4,5]])
print(speed)
add= dis+speed
print(add)

[[100  20 300]
 [ 10  20 300]]
[[1 3 4]
 [2 4 5]]
[[101  23 304]
 [ 12  24 305]]


In [37]:
r=np.random.random(24).reshape((2,3,4))
r.shape
r

array([[[0.48660942, 0.48899853, 0.22108622, 0.56324508],
        [0.76514564, 0.51979538, 0.16672932, 0.98256635],
        [0.07045629, 0.14637214, 0.70520368, 0.5015133 ]],

       [[0.12497594, 0.9804005 , 0.14371725, 0.88733065],
        [0.18427454, 0.86871004, 0.57315943, 0.45713392],
        [0.5727725 , 0.9376402 , 0.83005969, 0.28419514]]])

In [38]:
# array initilization
# filling with same value
np.full((2,3),10)

array([[10, 10, 10],
       [10, 10, 10]])

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [44]:
np.full((3,3),1)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [47]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [53]:
x= np.linspace(5,10,40)

In [54]:
x

array([ 5.        ,  5.12820513,  5.25641026,  5.38461538,  5.51282051,
        5.64102564,  5.76923077,  5.8974359 ,  6.02564103,  6.15384615,
        6.28205128,  6.41025641,  6.53846154,  6.66666667,  6.79487179,
        6.92307692,  7.05128205,  7.17948718,  7.30769231,  7.43589744,
        7.56410256,  7.69230769,  7.82051282,  7.94871795,  8.07692308,
        8.20512821,  8.33333333,  8.46153846,  8.58974359,  8.71794872,
        8.84615385,  8.97435897,  9.1025641 ,  9.23076923,  9.35897436,
        9.48717949,  9.61538462,  9.74358974,  9.87179487, 10.        ])

In [56]:
# arrawy iinspection 
x.shape



(40,)

In [57]:
x.size

40

In [58]:
x.ndim

1

In [59]:
x.dtype

dtype('float64')

In [60]:
np.median(x)

7.5

In [61]:
np.mean(x)

7.5

In [62]:
np.std(x)

1.4799226128993839