In [1]:
import numpy as np


In [5]:
# 1.Reverse the rows of a 2D array arr.
arr = np.arange(9).reshape(3,3)
# arr
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [6]:
# 2.Reverse the columns of a 2D array arr.
arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [7]:
# 3.Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.58547278 7.57232316 7.28263959]
 [6.27819522 8.34549718 9.53920081]
 [7.24192883 6.27108334 8.31726127]
 [9.60454945 9.61163282 9.96930084]
 [6.70208845 7.52157862 9.45768183]]


In [9]:
# 4.Print or show only 3 decimal places of the numpy array rand_arr.
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=4)
rand_arr[:4]

array([[0.4683, 0.9267, 0.4276],
       [0.1736, 0.4401, 0.7901],
       [0.3496, 0.1783, 0.869 ],
       [0.9309, 0.6495, 0.5072]])

In [12]:
# 5. Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

In [14]:
# 6. Limit the number of items printed in python numpy array a to a maximum of 6 elements.
np.set_printoptions(threshold=6)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [19]:
# 7.Import the iris dataset keeping the text intact.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)