In [8]:
import numpy as np

In [9]:
a= np.random.randint(1,10,10)
a

array([7, 7, 4, 7, 7, 2, 3, 2, 3, 5])

In [10]:
a[:3]

array([7, 7, 4])

In [11]:
a[-3:1]

array([], dtype=int32)

In [12]:
a[:3:]

array([7, 7, 4])

In [13]:
x= np.array([[1,3,4],[20,40,40]])
x

array([[ 1,  3,  4],
       [20, 40, 40]])

In [14]:
x[1,2]

40

In [15]:
x[1,0]

20

In [16]:
x[:,1:]

array([[ 3,  4],
       [40, 40]])

In [17]:
a[0:3]

array([7, 7, 4])

In [18]:
y=np.array([[100,30,44],[10,80,90]])
y

array([[100,  30,  44],
       [ 10,  80,  90]])

In [19]:
np.concatenate((x,y), axis = 0)

array([[  1,   3,   4],
       [ 20,  40,  40],
       [100,  30,  44],
       [ 10,  80,  90]])

In [20]:
np.vstack((x,y))

array([[  1,   3,   4],
       [ 20,  40,  40],
       [100,  30,  44],
       [ 10,  80,  90]])

In [21]:
np.hstack((x,y))

array([[  1,   3,   4, 100,  30,  44],
       [ 20,  40,  40,  10,  80,  90]])

In [22]:
np.column_stack((x,y))

array([[  1,   3,   4, 100,  30,  44],
       [ 20,  40,  40,  10,  80,  90]])

In [23]:
np.hsplit(x,1)

[array([[ 1,  3,  4],
        [20, 40, 40]])]

In [24]:
#  give an array  , all odd numbers muct be replayed with -1
arr= np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.where(a%2==1,-1,a)

array([-1, -1,  4, -1, -1,  2, -1,  2, -1, -1])

In [26]:
#  common element between two arrays

In [27]:
ar1 = np.array([0, 1, 2, 3, 4])
ar2 = [1, 3, 4]
  
# Common values between two arrays
print(np.intersect1d(ar1, ar2))

[1 3 4]


In [28]:
# swap 2 rowns in an array 
a= np.arange(9).reshape(3,3)

In [29]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
b=a[[0, 1,0]] = a[[1, 0,0]]

In [31]:
b

array([[3, 4, 5],
       [0, 1, 2],
       [0, 1, 2]])

In [32]:
# Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)


In [33]:
c=np.concatenate((a,b), axis=0)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [34]:
# tack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)


In [35]:
print(np.hstack((a,b)))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [36]:
 # Create the following pattern without hardcoding. Use only numpy functions and the below input array a
a = np.array([1,2,3])

In [37]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [38]:
# Q. Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [39]:
print(np.intersect1d(a,b))

[2 4]


In [40]:
# From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [41]:
b=np.delete(b,2, axis=0)

In [42]:
b

array([5, 6, 8, 9])