In [23]:
import numpy as np

In [24]:
# 1.Create a 1D array of numbers from 0 to 9
x= np.arange(10)
print(x)
x.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [25]:
# 2.Create a 3×3 numpy array of all True’s
y= np.full((3, 3), True, dtype=bool)
print(y)
y.dtype

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


dtype('bool')

In [26]:
#  alternative
y1= np.ones((3,3), dtype=bool)
print(y1)
y1.dtype

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


dtype('bool')

In [27]:
# 3.Extract all odd numbers from
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# arr
arr0=arr[arr % 2 != 0]
print(arr0)
# alternative methord
arr1=arr[arr% 2==1]
print(arr1)

[1 3 5 7 9]
[1 3 5 7 9]


In [31]:
# 4.Replace all odd numbers in arr with -1
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 != 0] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
# alternate methord 
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [37]:
# 5.Stack arrays a and b vertically
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b], axis= 0))

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [41]:
# 6.Stack the arrays a and b horizontally.
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(np.concatenate([a,b],axis=1))

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [42]:
# 7. Create the following pattern without hardcoding. Use only numpy functions and the below input array a
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [43]:
# 8.Get the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [44]:
# 9.From array a remove all items present in array b
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [45]:
# 10 Get the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)